/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/* 
 * File:   Hailstone.c
 * Author: USER
 *
 * Created on October 28, 2019, 2:59 PM
 */

#include <stdio.h>
#include <stdlib.h>

void hailstones(int);
int n;
int cnt = 0, hcnt = 0;

int main(void) {
    printf("\t\t\t::::THE HAILSTONE NUMBER::::\n\n");
    printf("\tEnter The Number: ");
    scanf("%d", &n);
    printf("\tHailstone Generated By %d:\n\n", n);
    while (n != 1) {
        hailstones(n);
    }
}

void hailstones(register int n) {
    while (n != 1) {
        if (n % 2 == 0) {
            n = n / 2;
            printf("\t%d\t", n);
            hcnt++, cnt++;
        } else {
            n = 3 * n + 1;
            printf("\t%d\t", n);
            hcnt++, cnt++;
        }
        if (cnt == 5) {
            putchar('\n');
            cnt = 0;
        }
        if (n == 1) {
            printf("\n\n%d Hailstone numbers generated", hcnt);
            exit(0);
        }
    }
}

